In [1]:
import os

print(os.getcwd())

C:\Users\ashis\Python

In [3]:
#2.Load the supplied dataset and identify the numerical features that will be used for clustering. Check for missing values and explain whether any data-cleaning action is required before modeling.
import pandas as pd

df = pd.read_csv("Food_Batch_Clustering_Day17_Dataset.csv")

print(df.head())

print(df.isnull().sum())

   temperature  moisture  storage_days    ph
0          7.7      32.8             6  5.41
1          6.0      34.3             3  5.56
2          9.1      33.6             8  5.51
3          9.6      35.7             3  6.21
4          8.2      29.4             1  5.54
temperature     0
moisture        0
storage_days    0
ph              0
dtype: int64

In [7]:
features = ['temperature', 'moisture', 'storage_days', 'ph']

X = df[features]

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [11]:
X_scaled[:5]

array([[-1.18891154, -1.08556022, -1.07924165, -1.45269995],
       [-1.42093867, -1.00128486, -1.42895092, -1.15307122],
       [-0.99783038, -1.04061336, -0.84610214, -1.25294746],
       [-0.92958711, -0.92262787, -1.42895092,  0.14531993],
       [-1.12066827, -1.27658436, -1.66209043, -1.19302172]])

In [12]:
X_scaled_df = pd.DataFrame(X_scaled, columns=features)

X_scaled_df.head()

   temperature  moisture  storage_days        ph
0    -1.188912 -1.085560     -1.079242 -1.452700
1    -1.420939 -1.001285     -1.428951 -1.153071
2    -0.997830 -1.040613     -0.846102 -1.252947
3    -0.929587 -0.922628     -1.428951  0.145320
4    -1.120668 -1.276584     -1.662090 -1.193022

In [15]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)

cluster_labels = kmeans.fit_predict(X_scaled)

In [14]:
df['Cluster'] = cluster_labels

df.head()

   temperature  moisture  storage_days    ph  Cluster
0          7.7      32.8             6  5.41        2
1          6.0      34.3             3  5.56        2
2          9.1      33.6             8  5.51        2
3          9.6      35.7             3  6.21        2
4          8.2      29.4             1  5.54        2

In [16]:
cluster_counts = df['Cluster'].value_counts().sort_index()

print(cluster_counts)

Cluster
0    40
1    40
2    40
Name: count, dtype: int64

In [17]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)

cluster_labels = kmeans.fit_predict(X_scaled)

df['Cluster'] = cluster_labels

print("Number of observations in each cluster:")
print(df['Cluster'].value_counts().sort_index())

Number of observations in each cluster:
Cluster
0    40
1    40
2    40
Name: count, dtype: int64

In [22]:
# Add cluster labels to the original dataset
df['cluster'] = kmeans.labels_

# Calculate mean of original numerical features for each cluster
cluster_summary = df.groupby('cluster')[X.columns].mean()

# Display the summary
print(cluster_summary)

         temperature  moisture  storage_days       ph
cluster
0            25.3075   73.1525        25.375  6.71375
1            15.8650   51.8800        14.575  6.10125
2             8.0600   31.3325         5.825  5.59675

In [23]:
print(cluster_summary)

         temperature  moisture  storage_days       ph
cluster
0            25.3075   73.1525        25.375  6.71375
1            15.8650   51.8800        14.575  6.10125
2             8.0600   31.3325         5.825  5.59675

In [24]:
#8Calculate either K-Means inertia or silhouette score for the 3-cluster solution. Report the value and briefly explain what it tells you about the cluster you about the clustering result.

from sklearn.metrics import silhouette_score

sil_score = silhouette_score(X_scaled, kmeans.labels_)

print("Silhouette Score:", sil_score)

Silhouette Score: 0.6086756907800501